name: Corin James Photography
favicon: null
layout_spectrum: 0.3222126201726496
typography_spectrum: 0.4391480106860399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9261660743504763
  lightness: 0.8346494503784925
  saturation: 0.8230591798201203
  rhythmicContrast: 0.9848671522922814
purpose: []
